variables:
  IMAGE: rigetti/lisp

.docker:
  image: docker:stable
  stage: deploy
  tags:
    - dockerd
    - github
  # only run when the IMAGE variable exists and is not null
  only:
    variables:
      - $IMAGE
  variables:
    LATEST: ${IMAGE}:latest
  before_script:
    - docker -v
    # needed for executing the Makefile
    - apk add make
    - echo ${IMAGE}
    - echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
    - eval VERSION=$(cat VERSION-QUICKLISP.txt)
    - RELEASE=${IMAGE}:${VERSION}
  after_script:
    - docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep ${IMAGE})

docker-edge:
  extends: .docker
  only:
    refs:
      - master
  script:
    - make
    - docker tag ${RELEASE} ${LATEST}
    - docker push ${RELEASE} && docker push ${LATEST}

docker-nightly:
  extends: .docker
  # matches only on the scheduled nightly build
  only:
    - schedules
  script:
    - make
    - docker tag ${RELEASE} ${LATEST}
    - docker push ${RELEASE} && docker push ${LATEST}

docker-test:
  extends: .docker
  # matches only on non-master branches
  only:
    refs:
      - branches
  except:
    refs:
      - master
  # just builds the docker image, without pushing
  script:
    - make
